### ISSUE TITLE
NameError: name 'List' is not defined

### ISSUE THREAD

**Issue by CherWeiYuan** [YStrauch/CI-SpliceAI__Annotation#2]
Dear Dr Yaron and Developers

Thank you for developing CI-SpliceAI. I think it is a useful improvement to SpliceAI.

I ran into the following error from running CI-SpliceAI. May I seek your assistance?

``mamba create -n cis_use python=3.8 tensorflow-gpu cudnn keras -c conda-forge -y``
``mamba activate cis_use``
``pip install "cispliceai"``
``cis-vcf -h``

Output:
Traceback (most recent call last):
  File "/home/weiyuan/mambaforge/envs/cis_use/bin/cis-vcf", line 5, in <module>
    from cispliceai.console import vcf
  File "/home/weiyuan/mambaforge/envs/cis_use/lib/python3.8/site-packages/cispliceai/__init__.py", line 2, in <module>
    from .annotation import Annotator, JSONFormatException, AnnotationJob, AnnotationJobWithResults, Annotation, AnnotationCache
  File "/home/weiyuan/mambaforge/envs/cis_use/lib/python3.8/site-packages/cispliceai/annotation.py", line 8, in <module>
    from cispliceai import const, progress, data
  File "/home/weiyuan/mambaforge/envs/cis_use/lib/python3.8/site-packages/cispliceai/data.py", line 65, in <module>
    class AnnotatedArea():
  File "/home/weiyuan/mambaforge/envs/cis_use/lib/python3.8/site-packages/cispliceai/data.py", line 75, in AnnotatedArea
    acceptors: List[int],
NameError: name 'List' is not defined

Notes:
The installation process went fine. I tried version control of dependencies with 
``mamba create -n cis_use python=3.8 tensorflow-gpu=2.2.0 cudnn=7.6.5.32=hc0a50b0_1 keras=2.4.3 -c conda-forge``
but I encountered this error:
Encountered problems while solving:
  - nothing provides requested tensorflow-gpu 2.2.0**

Thank you for your attention.

Best Regards
WY

**Comment by CherWeiYuan** [comment]
Fixed by adding `from typing import List` to cispliceai/data.py

**Comment by YStrauch** [comment]
Closed with #3 and released in V1.1.1
