### ISSUE TITLE
CI-spliceAI crashed due to M nucleotide in hg38

### ISSUE THREAD

**Issue by ymcki** [YStrauch/CI-SpliceAI__Annotation#4]
I am getting this error with the GPU version of CI-spliceAI

Traceback (most recent call last):
  File "/nfs/home/abc/miniconda3/envs/py38gpu/bin/cis-vcf", line 8, in <module>
    sys.exit(vcf())
  File "/nfs/home/abc/miniconda3/envs/py38gpu/lib/python3.8/site-packages/cispliceai/console.py", line 46, in vcf
    annotator.annotate_vcf(
  File "/nfs/home/abc/miniconda3/envs/py38gpu/lib/python3.8/site-packages/cispliceai/annotation.py", line 440, in annotate_vcf
    jobs = self.run_jobs(jobs)
  File "/nfs/home/abc/miniconda3/envs/py38gpu/lib/python3.8/site-packages/cispliceai/annotation.py", line 299, in run_jobs
    self._run_batches(jobs_to_run)
  File "/nfs/home/abc/miniconda3/envs/py38gpu/lib/python3.8/site-packages/cispliceai/annotation.py", line 314, in _run_batches
    for jobs_batch, error in self._create_ml_batches(jobs):
  File "/nfs/home/abc/miniconda3/envs/py38gpu/lib/python3.8/site-packages/cispliceai/annotation.py", line 352, in _create_ml_batches
    ml_data = self.preprocessor.get_ml_data(job.variant)
  File "/nfs/home/abc/miniconda3/envs/py38gpu/lib/python3.8/site-packages/cispliceai/data.py", line 149, in get_ml_data
    x = self._onehot_seq(seq)
  File "/nfs/home/abc/miniconda3/envs/py38gpu/lib/python3.8/site-packages/cispliceai/data.py", line 192, in _onehot_seq
    num = np.asarray(list(map(int, list(num))))
ValueError: invalid literal for int() with base 10: 'M'

Based on my understanding of cispliceai/data.py, I think it is due to CI-SpliceAI doesn't handle M nucleotide in hg38 when doing one 
 hot encoding:

    @classmethod
    def _onehot_seq(cls, seq):
        if seq == '':
            return np.zeros((0, 4))
        num = seq.upper().replace('N', '0').replace('A', '1').replace('C', '2').replace('G', '3').replace('T', '4')
        num = np.asarray(list(map(int, list(num))))

        return cls.ONE_HOT[num]

Having said that, it is strange that this error can occur as hg38 should be extensively tested, so maybe my guess is wrong???

**Comment by ymcki** [comment]
The genome you recommend has no M nucleotides, so it works with CI-SpliceAI
https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/latest_release/GRCh38.primary_assembly.genome.fa.gz
but my genome has M nucleotides. Is it ok if I use vcf generated with my genome but use your reference genome for CI-SpliceAI?
ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/001/405/GCA_000001405.15_GRCh38/seqs_for_alignment_pipelines.ucsc_ids/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gz
Is it possible to make CI-SpliceAI to support genomes with IUPAC nucleotide?

**Comment by YStrauch** [comment]
CI-SpliceAI only supports A/C/G/T nuceotides. Implementing others would require a general revamp of the code base and new ML training. That means unfortunately, I see no viable way of doing what you need without substantial development and re-training.

I do not advise aligning your VCF to one genome and running ML inference on another. CI-SpliceAI extracts and infers on long DNA sequences based on the position/ref/alt from the VCF file and the sequences in the matching reference genome, if these are not in synch, outputs are not meaningful.
